import 'package:flutter/material.dart';
import 'package:flutter_svg/svg.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Profile(),
        ]),
      ),
    );
  }
}

class Profile extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 390,
          height: 844,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Color(0xFFF5FBF6),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(50),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 390,
                  height: 350,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 390,
                          height: 160,
                          decoration: BoxDecoration(color: Color(0xFF4B635A)),
                        ),
                      ),
                      Positioned(
                        left: 30,
                        top: 30,
                        child: Container(
                          width: 40,
                          height: 40,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 40,
                                  height: 40,
                                  decoration: const BoxDecoration(
                                    color: Color(0xFFA3F2D7),
                                    shape: BoxShape.circle,
                                  ),
                                  child: Center(
                                    child: SvgPicture.asset(
                                      'assets/icons_smartphone/boton_atras.svg',
                                      width: 24,
                                      height: 24,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 135,
                        top: 100,
                        child: Container(
                          width: 120,
                          height: 120,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 120,
                                  height: 120,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFD9D9D9),
                                    shape: OvalBorder(),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 101,
                        top: 231,
                        child: Text(
                          'Ricardo Murillo',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 28,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w400,
                            height: 0.05,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 769,
                child: Container(
                  width: 390,
                  height: 75,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 390,
                          height: 75,
                          decoration: BoxDecoration(color: Color(0xFFF5FBF6)),
                        ),
                      ),
                      Positioned(
                        left: 35,
                        top: 18,
                        child: Container(
                          width: 40,
                          height: 40,
                          child: SvgPicture.asset(
                            'assets/icons_smartphone/menu/silbatoClicked.svg',
                            width: 40,
                            height: 40,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 105,
                        top: 18,
                        child: Container(
                          width: 40,
                          height: 40,
                          child: SvgPicture.asset(
                            'assets/icons_smartphone/menu/reporting.svg',
                            width: 40,
                            height: 40,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 175,
                        top: 18,
                        child: Container(
                          width: 40,
                          height: 40,
                          child: SvgPicture.asset(
                            'assets/icons_smartphone/menu/home.svg',
                            width: 40,
                            height: 40,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 245,
                        top: 18,
                        child: Container(
                          width: 40,
                          height: 40,
                          child: SvgPicture.asset(
                            'assets/icons_smartphone/menu/schedule.svg',
                            width: 40,
                            height: 40,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 315,
                        top: 18,
                        child: Container(
                          width: 40,
                          height: 40,
                          child: SvgPicture.asset(
                            'assets/icons_smartphone/menu/settings.svg',
                            width: 40,
                            height: 40,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}