// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApDQdEVPB9KXUlFBi4R6zaCRoATfX4mVw',
    appId: '1:1029243904025:web:558c7e23fddd4e1ced8a88',
    messagingSenderId: '1029243904025',
    projectId: 'whistle-time-7cc21',
    authDomain: 'whistle-time-7cc21.firebaseapp.com',
    storageBucket: 'whistle-time-7cc21.firebasestorage.app',
    measurementId: 'G-YVWMMFDP0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKM1lXRRN5ge3NDV8StR80V1qN94BRwkE',
    appId: '1:1029243904025:android:1ae58e7be68624d5ed8a88',
    messagingSenderId: '1029243904025',
    projectId: 'whistle-time-7cc21',
    storageBucket: 'whistle-time-7cc21.firebasestorage.app',
  );

}